const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphone - Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Airpods Wireless Bluetooth Headphone - Alexa",
    image: "/images/alexa.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 2.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Airpods Wireless Bluetooth Headphone - Camera",
    image: "/images/Camera.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Airpods Wireless Bluetooth Headphone - Mouse",
    image: "/images/mouse.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Airpods Wireless Bluetooth Headphone - Phone",
    image: "/images/phone.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 1.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Airpods Wireless Bluetooth Headphone - Playstation",
    image: "/images/playstation.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 10,
    rating: 0.5,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Airpods Wireless Bluetooth Headphone - Sample",
    image: "/images/sample.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem at est ab, quod sapiente odit inventore soluta! Velit labore reiciendis voluptates qui optio animi veritatis repellendus, eius facere fuga voluptatibus.",
    brand: "Apple",
    category: "Electronics",
    price: 88.99,
    countInStock: 0,
    rating: 5,
    numReviews: 12,
  },
];

export default products;